[package]
name = "process_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29.0"
chrono = "0.4.26"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
log = "0.4.19"
env_logger = "0.10.0"
tokio = { version = "1.29.1", features = ["full"] } 